// Generated by CoffeeScript 1.6.2
(function() {
  var extendURL, g, _ref;

  if ((_ref = this.vichrome) == null) {
    this.vichrome = {};
  }

  g = this.vichrome;

  extendURL = function(base) {
    var url;

    if (base.search(/^javascript:/i) >= 0) {
      return base;
    }
    if (base.indexOf("%clipboard") >= 0) {
      url = encodeURI(base.replace(/%clipboard/g, g.clipboard.get()));
    } else {
      url = encodeURI(base);
    }
    if (url.indexOf("://") < 0) {
      url = "http://" + url;
    }
    return url;
  };

  g.bg = {
    tabHistory: null,
    moveTab: function(offset, start, callback) {
      return chrome.tabs.getAllInWindow(null, function(tabs) {
        var nTabs;

        nTabs = tabs.length;
        return chrome.tabs.getSelected(null, function(tab) {
          var idx;

          if (start != null) {
            idx = start + offset;
          } else {
            idx = tab.index + offset;
          }
          if (idx < 0) {
            idx = nTabs + (idx % nTabs);
          } else if (idx >= nTabs) {
            idx = idx % nTabs;
          }
          return chrome.tabs.update(tabs[idx].id, {
            selected: true
          }, callback);
        });
      });
    },
    getSettings: function(msg) {
      var sendMsg;

      sendMsg = {};
      sendMsg.name = msg.name;
      if (msg.name === "all") {
        sendMsg.value = g.SettingManager.getAll();
      } else {
        sendMsg.value = g.SettingManager.get(msg.name);
      }
      return sendMsg;
    },
    setSettings: function(msg, response) {
      g.SettingManager.set(msg.name, msg.value);
      return {};
    },
    reqSettings: function(msg, response) {
      if (msg.type === "get") {
        response(this.getSettings(msg));
      } else if (msg.type === "set") {
        response(this.setSettings(msg));
      }
      return true;
    },
    reqInit: function(msg, response, sender) {
      var o;

      o = this.getSettings({
        name: "all"
      });
      o.command = "Init";
      g.logger.d("frameID " + (this.tabHistory.getFrames(sender.tab)) + " added");
      o.frameID = this.tabHistory.getFrames(sender.tab);
      this.tabHistory.addFrames(sender.tab);
      response(o);
      return true;
    },
    getDefaultNewTabPage: function() {
      switch (g.SettingManager.get("defaultNewTab")) {
        case "home":
          return void 0;
        case "newtab":
          return "chrome://newtab";
        case "blank":
          return "about:blank";
      }
    },
    reqTabOpenNew: function(req) {
      var arg, extend, focus, len, next, pinned, times, urls, _i, _len, _ref1, _ref2, _ref3,
        _this = this;

      urls = [];
      focus = true;
      pinned = false;
      extend = (_ref1 = req.extend) != null ? _ref1 : false;
      _ref2 = req.args;
      for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
        arg = _ref2[_i];
        switch (arg) {
          case "-b":
          case "--background":
            focus = false;
            break;
          case "-p":
          case "--pinned":
            pinned = true;
            break;
          case "--next":
            next = true;
            break;
          default:
            urls.push(arg);
        }
      }
      len = urls.length;
      times = (_ref3 = req.times) != null ? _ref3 : 1;
      chrome.tabs.getSelected(null, function(tab) {
        var index, url, _j, _len1;

        if (next) {
          index = tab.index + 1;
        }
        if (len === 0) {
          while (times--) {
            chrome.tabs.create({
              url: _this.getDefaultNewTabPage(),
              selected: focus,
              pinned: pinned,
              index: index
            });
          }
        } else {
          for (_j = 0, _len1 = urls.length; _j < _len1; _j++) {
            url = urls[_j];
            if (extend) {
              url = extendURL(url);
            }
            chrome.tabs.create({
              url: url,
              selected: focus,
              pinned: pinned,
              index: index
            });
          }
        }
      });
      return false;
    },
    reqCopy: function(req) {
      return chrome.tabs.getSelected(null, function(tab) {
        var c, data;

        data = req.args[0].replace(/%url/g, tab.url).replace(/%title/g, tab.title);
        c = data.charAt(0);
        if (c === "'" || c === "\"") {
          if (data.charAt(data.length - 1) === c) {
            data = data.substr(1, data.length - 2);
          }
        }
        return g.clipboard.set(data);
      });
    },
    reqWinOpenNew: function(req) {
      var arg, focus, pop, urls, _i, _len, _ref1;

      urls = [];
      focus = true;
      pop = false;
      _ref1 = req.args;
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        arg = _ref1[_i];
        switch (arg) {
          case "-b":
          case "--background":
            focus = false;
            break;
          case "-p":
          case "--pop":
            pop = true;
            break;
          default:
            urls.push(arg.replace(/%url/g, g.view.getHref()));
        }
      }
      if (pop) {
        chrome.tabs.getSelected(null, function(tab) {
          if (urls.length === 0) {
            return chrome.windows.create({
              focused: focus,
              tabId: tab.id
            });
          } else {
            return chrome.windows.create({
              url: urls,
              focused: focus,
              tabId: tab.id
            });
          }
        });
      } else {
        if (urls.length === 0) {
          urls = this.getDefaultNewTabPage();
        }
        chrome.windows.create({
          url: urls,
          focused: focus
        });
      }
      return false;
    },
    reqTabCloseCurrent: function(req) {
      var arg, prev, _i, _len, _ref1,
        _this = this;

      _ref1 = req.args;
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        arg = _ref1[_i];
        switch (arg) {
          case "--focusprev":
            prev = true;
        }
      }
      chrome.tabs.getSelected(null, function(tab) {
        if (prev && tab.index > 0) {
          return _this.moveTab(-1, tab.index, function() {
            return chrome.tabs.remove(tab.id);
          });
        } else {
          return chrome.tabs.remove(tab.id);
        }
      });
      return false;
    },
    reqTabCloseAll: function(req) {
      var arg, only, _i, _len, _ref1;

      _ref1 = req.args;
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        arg = _ref1[_i];
        switch (arg) {
          case "--only":
            only = true;
        }
      }
      if (only) {
        chrome.tabs.getAllInWindow(null, function(tabs) {
          return chrome.tabs.getSelected(null, function(selected) {
            var tab, _j, _len1;

            for (_j = 0, _len1 = tabs.length; _j < _len1; _j++) {
              tab = tabs[_j];
              if (selected.id !== tab.id) {
                chrome.tabs.remove(tab.id);
              }
            }
          });
        });
      } else {
        chrome.windows.getCurrent(function(win) {
          return chrome.windows.remove(win.id);
        });
      }
      return false;
    },
    reqTabReloadAll: function(req) {
      var _ref1;

      if ((_ref1 = g.tabs) != null) {
        if (typeof _ref1.reloadAllTabs === "function") {
          _ref1.reloadAllTabs();
        }
      }
      return false;
    },
    reqTabFocusNext: function(req) {
      var _ref1;

      if (((_ref1 = req.args) != null ? _ref1[0] : void 0) != null) {
        if (req.args[0] <= 0) {
          return;
        }
        this.moveTab(parseInt(req.args[0]) - 1, 0);
      } else {
        if (req.timesSpecified && req.times > 0) {
          this.moveTab(req.times - 1, 0);
        } else {
          this.moveTab(1);
        }
      }
      return false;
    },
    reqTabFocusPrev: function(req) {
      var times, _ref1;

      times = req.times ? req.times : 1;
      if (((_ref1 = req.args) != null ? _ref1[0] : void 0) != null) {
        this.moveTab(-parseInt(req.args[0]));
      } else {
        this.moveTab(-times);
      }
      return false;
    },
    reqTabFocusNextHistory: function(req) {
      this.tabSelHist.moveForward();
      return false;
    },
    reqTabFocusPrevHistory: function(req) {
      this.tabSelHist.moveBackward();
      return false;
    },
    reqTabSwitchLast: function(req) {
      this.tabSelHist.switchToLast();
      return false;
    },
    reqTabFocusFirst: function(req) {
      this.moveTab(0, 0);
      return false;
    },
    reqTabFocusLast: function(req) {
      this.moveTab(-1, 0);
      return false;
    },
    reqRestoreTab: function(req) {
      this.tabHistory.restoreLastClosedTab();
      return false;
    },
    reqNMap: function(req, sendResponse) {
      var msg;

      if (!((req.args[0] != null) && (req.args[1] != null))) {
        return;
      }
      msg = {
        command: "Settings",
        name: "keyMappingNormal",
        value: g.SettingManager.setNMap(req.args)
      };
      sendResponse(msg);
      return true;
    },
    reqIMap: function(req, sendResponse) {
      var msg;

      if (!((req.args[0] != null) && (req.args[1] != null))) {
        return;
      }
      msg = {
        command: "Settings",
        name: "keyMappingInsert",
        value: g.SettingManager.setIMap(req.args)
      };
      sendResponse(msg);
      return true;
    },
    reqAlias: function(req, sendResponse) {
      var msg;

      if (!((req.args[0] != null) && (req.args[1] != null))) {
        return;
      }
      msg = {
        command: "Settings",
        name: "aliases",
        value: g.SettingManager.setAlias(req.args)
      };
      sendResponse(msg);
      return true;
    },
    reqReadability: function(req) {
      chrome.tabs.getSelected(null, function(tab) {
        return chrome.extension.sendRequest("jggheggpdocamneaacmfoipeehedigia", {
          type: "render",
          tab_id: tab.id
        });
      });
      return false;
    },
    reqPushSearchHistory: function(req) {
      var history, idx;

      if (req.value == null) {
        return;
      }
      history = JSON.parse(localStorage.getItem("_searchHistory"));
      history || (history = []);
      if ((idx = history.indexOf(req.value)) >= 0) {
        history.splice(idx, 1);
      }
      history.push(req.value);
      if (history.length > 10) {
        history.shift();
      }
      localStorage.setItem("_searchHistory", JSON.stringify(history));
      return false;
    },
    reqGetSearchHistory: function(req, sendResponse) {
      var history, msg;

      history = JSON.parse(localStorage.getItem("_searchHistory"));
      msg = {
        command: "GetSearchHistory",
        value: history
      };
      sendResponse(msg);
      return true;
    },
    reqGetBookmark: function(req, sendResponse) {
      chrome.bookmarks.search(req.value, function(nodes) {
        return sendResponse(nodes);
      });
      return true;
    },
    reqGetHistory: function(req, sendResponse) {
      chrome.history.search({
        text: req.value,
        maxResults: 5
      }, function(items) {
        return sendResponse(items);
      });
      return true;
    },
    reqGetGoogleSuggest: function(req, sendResponse) {
      if (!this.gglLoaded) {
        return false;
      }
      if (this.cWSrch.isExec) {
        return false;
      }
      this.cWSrch.reset().sgst({
        kw: req.value,
        hl: g.util.getLang(),
        res: function(res) {
          return sendResponse(res.raw);
        }
      }).start();
      return true;
    },
    reqGetWebSuggest: function(req, sendResponse) {
      var _this = this;

      if (!this.gglLoaded) {
        return false;
      }
      if (this.cWSrch.isExec) {
        return false;
      }
      this.cWSrch.init({
        type: "web",
        opt: function(obj) {
          return obj.setResultSetSize(google.search.Search.LARGE_RESULTSET);
        }
      }).start();
      this.cWSrch.reset().srch({
        type: "web",
        page: 1,
        key: req.value,
        res: function(res) {
          var i, item, msg, obj, _i, _len;

          if (!res || res.length <= 0) {
            _this.cWSrch.cmndsBreak();
            sendResponse();
            return;
          }
          msg = [];
          for (i = _i = 0, _len = res.length; _i < _len; i = ++_i) {
            item = res[i];
            obj = {};
            obj.titleNoFormatting = item.titleNoFormatting;
            obj.unescapedUrl = item.unescapedUrl;
            obj.url = item.url;
            msg.push(obj);
          }
          return sendResponse(msg);
        }
      }).start();
      return true;
    },
    reqGetTabList: function(req, sendResponse) {
      chrome.tabs.getAllInWindow(null, function(tabs) {
        return sendResponse(tabs);
      });
      return true;
    },
    reqOpenOptionPage: function(req) {
      var arg, key, url, _i, _len, _ref1;

      _ref1 = req.args;
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        arg = _ref1[_i];
        switch (arg) {
          case "-k":
          case "--key":
            key = true;
        }
      }
      req = {};
      req.args = [];
      req.times = 1;
      url = chrome.extension.getURL("options.html");
      if (key) {
        url += "#keymapping";
      }
      req.args.push(url);
      return this.reqTabOpenNew(req);
    },
    reqTopFrame: function(req, response, sender) {
      var o;

      req.command = req.innerCommand;
      req.frameID = this.tabHistory.getTopFrameID(sender.tab);
      if (req.frameID != null) {
        chrome.tabs.sendRequest(sender.tab.id, req);
      } else {
        g.logger.e("Can't send request to top frame: frame ID is invalid");
        o = {};
        o.error = true;
        o.errorMsg = "Something's wrong. Try to reload page";
        response(o);
        return true;
      }
      return false;
    },
    reqPassToFrame: function(req, response, sender) {
      req.command = req.innerCommand;
      chrome.tabs.sendRequest(sender.tab.id, req);
      return false;
    },
    reqSendToCommandBox: function(req, response, sender) {
      var o;

      req.command = req.innerCommand;
      req.frameID = this.tabHistory.getCommandBoxID(sender.tab);
      if (req.frameID != null) {
        chrome.tabs.sendRequest(sender.tab.id, req);
      } else {
        g.logger.e("Can't send request to command box: frame ID is invalid");
        o = {};
        o.error = true;
        o.errorMsg = "Can't open commandbox. Try to reload page";
        response(o);
        return true;
      }
      return false;
    },
    reqGetCommandTable: function(req, response, sender) {
      req.frameID = this.tabHistory.getTopFrameID(sender.tab);
      chrome.tabs.sendRequest(sender.tab.id, req, function(msg) {
        return response(msg);
      });
      return true;
    },
    reqGetAliases: function(req, response, sender) {
      req.frameID = this.tabHistory.getTopFrameID(sender.tab);
      chrome.tabs.sendRequest(sender.tab.id, req, function(msg) {
        return response(msg);
      });
      return true;
    },
    reqGetClipboard: function(req, response, sender) {
      response(g.clipboard.get());
      return true;
    },
    reqExtendURL: function(req, response, sender) {
      response(extendURL(req.url));
      return true;
    },
    init: function() {
      var $WA, req, storedVersion,
        _this = this;

      this.tabHistory = (new g.TabHistory).init();
      this.tabSelHist = (new g.TabSelectionHistory).init();
      g.SettingManager.init();
      $WA = crocro.webAi;
      this.cWSrch = new $WA.WebSrch();
      this.cWSrch.ready(function() {
        return _this.gglLoaded = true;
      });
      chrome.extension.onRequest.addListener(function(req, sender, sendResponse) {
        var frameID, msg;

        g.logger.d("onRequest command: " + req.command);
        switch (req.command) {
          case "NotifyTopFrame":
            g.logger.d("top frame " + req.frameID);
            _this.tabHistory.setTopFrameID(sender.tab, req.frameID);
            return sendResponse();
          case "InitCommandFrame":
            msg = {};
            frameID = _this.tabHistory.getFrames(sender.tab);
            _this.tabHistory.setCommandBoxID(sender.tab, frameID);
            _this.tabHistory.addFrames(sender.tab);
            g.logger.d("commandBoxFrameID: " + frameID);
            msg.frameID = frameID;
            msg.enableCompletion = g.SettingManager.get("enableCompletion");
            msg.commandBoxWidth = g.SettingManager.get("commandBoxWidth");
            msg.commandBoxAlign = g.SettingManager.get("commandBoxAlign");
            msg.commandWaitTimeOut = g.SettingManager.get("commandWaitTimeOut");
            return sendResponse(msg);
          default:
            if (_this["req" + req.command]) {
              if (!_this["req" + req.command](req, sendResponse, sender)) {
                return sendResponse();
              }
            } else {
              return g.logger.e("INVALID command!:", req.command);
            }
        }
      });
      if (g.SettingManager.get("notifyUpdateSucceeded")) {
        storedVersion = localStorage.version;
        if ((storedVersion != null) && storedVersion !== g.VICHROME_VERSION) {
          req = {};
          req.args = ["https://github.com/k2nr/ViChrome/wiki/Release-History"];
          this.reqTabOpenNew(req);
        }
      }
      return localStorage.version = g.VICHROME_VERSION;
    }
  };

  g.bg.init();

}).call(this);
