// Generated by CoffeeScript 1.3.3
(function() {
  var g, _ref;

  if ((_ref = this.vichrome) == null) {
    this.vichrome = {};
  }

  g = this.vichrome;

  g.storage = {
    set: function(items, callback) {
      return storage.set;
    },
    remove: function(keys, callback) {}
  };

}).call(this);
